#all parts that are adaptions of part 100

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sphaera: <http://ontologies.mpiwg-berlin.mpg.de/sphaera/>
PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX sphType: <http://sphaera.mpiwg-berlin.mpg.de/id/thes/type/>

SELECT
                    ?adaption
                    ?adaption_label
					?custom_identifier
                    ?creator
                    
					(GROUP_CONCAT(DISTINCT ?creator_label; SEPARATOR=", ") as ?creators)
                    (COUNT(DISTINCT ?book) as ?num_books)
                    (GROUP_CONCAT(DISTINCT ?adaption_type; SEPARATOR=", ") as ?adaption_types)
                  WHERE { {
                  ?adaption a sphaera:Part_Adaption ;
                    ecrm:P2_has_type/ecrm:P3_has_note ?adaption_type ;
                    (ecrm:P106_is_composed_of/ecrm:P165_incorporates)|(efrbroo:R3i_realises/^efrbroo:R40i_is_representative_expression_for) ?part ;
                      ecrm:P3_has_note ?adaption_label .
  					 ?adaption ecrm:P1_is_identified_by ?identifier .
          			?identifier ecrm:P2_has_type sphaera:customIdentifier ;
          				ecrm:P3_has_note ?custom_identifier .

                  OPTIONAL {
                    ?adaption efrbroo:R17i_was_created_by/ecrm:PC01_is_domain_of/ecrm:PC02_has_range ?creator .
                    ?creator ecrm:P48_has_preferred_identifier/ecrm:P3_has_note ?creator_label.
                  }

                  OPTIONAL {
                    ?book ecrm:P128_carries/ecrm:P165_incorporates/ecrm:P148_has_component ?adaption .
                  }
                  #[[> :queryFormatName input="?creator_label" output="?creator_name"]]
                  BIND(<http://sphaera.mpiwg-berlin.mpg.de/id/part/c6145ca3-317c-4724-a344-3c2e106fe26b> as ?part)

 }

}GROUP BY ?adaption ?adaption_label ?custom_identifier ?creator