PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sphaera: <http://ontologies.mpiwg-berlin.mpg.de/sphaera/>
PREFIX ecrm: <http://erlangen-crm.org/current/>

SELECT ?images ?label ?uck ?level WHERE {
  { ?x a sphaera:Element;
    ecrm:P3_has_note ?label .
    ?x ^ecrm:P138_represents ?images.
    ?x ecrm:P2_has_type ?note.
    ?note ecrm:P3_has_note ?uck.
    BIND (0 AS ?level)
  } UNION {
    ?x a sphaera:Element;
    ecrm:P3_has_note ?label .
    ?x ^ecrm:P138_represents ?images.
    ?x ecrm:P2_has_type ?note.
    ?note ^sphaera:hierarchicallink ?uckid.
    ?uckid ecrm:P3_has_note ?uck.
    BIND (1 AS ?level)
  } UNION {
    ?x a sphaera:Element;
    ecrm:P3_has_note ?label .
    ?x ^ecrm:P138_represents ?images.
    ?x ecrm:P2_has_type ?note.
    ?note ^sphaera:hierarchicallink ?uckid.
    ?uckid ^sphaera:hierarchicallink ?uckid2.
    ?uckid2 ecrm:P3_has_note ?uck.
    BIND (2 AS ?level)
  } UNION {
    ?x a sphaera:Element;
    ecrm:P3_has_note ?label .
    ?x ^ecrm:P138_represents ?images.
    ?x ecrm:P2_has_type ?note.
    ?note ^sphaera:hierarchicallink ?uckid.
    ?uckid ^sphaera:hierarchicallink ?uckid2.
    ?uckid2 ^sphaera:hierarchicallink ?uckid3.
    ?uckid3 ecrm:P3_has_note ?uck.
    BIND (3 AS ?level)
  } UNION{
    ?x a sphaera:Element;
    ecrm:P3_has_note ?label .
    ?x ^ecrm:P138_represents ?images.
    ?x ecrm:P2_has_type ?note.
    ?note ^sphaera:hierarchicallink ?uckid.
    ?uckid ^sphaera:hierarchicallink ?uckid2.
    ?uckid2 ^sphaera:hierarchicallink ?uckid3.
    ?uckid3 ^sphaera:hierarchicallink ?uckid4.
    ?uckid4 ecrm:P3_has_note ?uck.
    BIND (4 AS ?level)
  }UNION{
    ?x a sphaera:Element;
    ecrm:P3_has_note ?label .
    ?x ^ecrm:P138_represents ?images.
    ?x ecrm:P2_has_type ?note.
    ?note ^sphaera:hierarchicallink ?uckid.
    ?uckid ^sphaera:hierarchicallink ?uckid2.
    ?uckid2 ^sphaera:hierarchicallink ?uckid3.
    ?uckid3 ^sphaera:hierarchicallink ?uckid4.
    ?uckid4 ^sphaera:hierarchicallink ?uckid5.
    ?uckid5 ecrm:P3_has_note ?uck.
    BIND (5 AS ?level)
  }UNION{
    ?x a sphaera:Element;
    ecrm:P3_has_note ?label .
    ?x ^ecrm:P138_represents ?images.
    ?x ecrm:P2_has_type ?note.
    ?note ^sphaera:hierarchicallink ?uckid.
    ?uckid ^sphaera:hierarchicallink ?uckid2.
    ?uckid2 ^sphaera:hierarchicallink ?uckid3.
    ?uckid3 ^sphaera:hierarchicallink ?uckid4.
    ?uckid4 ^sphaera:hierarchicallink ?uckid5.
    ?uckid5 ^sphaera:hierarchicallink ?uckid6.
    ?uckid6 ecrm:P3_has_note ?uck.
    BIND (6 AS ?level)
  }UNION{
    ?x a sphaera:Element;
    ecrm:P3_has_note ?label .
    ?x ^ecrm:P138_represents ?images.
    ?x ecrm:P2_has_type ?note.
    ?note ^sphaera:hierarchicallink ?uckid.
    ?uckid ^sphaera:hierarchicallink ?uckid2.
    ?uckid2 ^sphaera:hierarchicallink ?uckid3.
    ?uckid3 ^sphaera:hierarchicallink ?uckid4.
    ?uckid4 ^sphaera:hierarchicallink ?uckid5.
    ?uckid5 ^sphaera:hierarchicallink ?uckid6.
    ?uckid6 ^sphaera:hierarchicallink ?uckid7.
    ?uckid7 ecrm:P3_has_note ?uck.
    BIND (7 AS ?level)
  }
  }


