PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sphaera: <http://ontologies.mpiwg-berlin.mpg.de/sphaera/>
PREFIX ecrm: <http://erlangen-crm.org/current/>
PREFIX efrbroo: <http://erlangen-crm.org/efrbroo/>
PREFIX sphType: <http://sphaera.mpiwg-berlin.mpg.de/id/thes/type/>

SELECT
                    ?influenced_part
                    ?influenced_part_label
					?custom_identifier
					?carried_out_by
					(GROUP_CONCAT(DISTINCT ?influenced_part_author; SEPARATOR=", ") as ?influenced_part_authors)
                    (COUNT(DISTINCT ?book) as ?num_books)
WHERE { {
                      ?event ecrm:P15_was_influenced_by ?part ;
                      ^efrbroo:R17i_was_created_by ?influenced_part .

                    ?influenced_part a ?part_type ;
                      ecrm:P3_has_note ?influenced_part_label .
      
      				 ?influenced_part ecrm:P1_is_identified_by ?identifier .
          			?identifier ecrm:P2_has_type sphaera:customIdentifier ;
          				ecrm:P3_has_note ?custom_identifier .

                    OPTIONAL {
                      ?influenced_part efrbroo:R17i_was_created_by/ecrm:PC01_is_domain_of ?carried_out_by .
                      ?carried_out_by a ecrm:PC14_carried_out_by ;
                  		ecrm:PC02_has_range/ecrm:P48_has_preferred_identifier/ecrm:P3_has_note ?influenced_part_author .
                      #[[> :queryFormatName input="?influenced_part_author" output="?influenced_part_author_label"]]
                    }
      
      				                  OPTIONAL {
                    ?book ecrm:P128_carries/ecrm:P165_incorporates/ecrm:P148_has_component ?influenced_part .
                  }

                    VALUES ( ?part_type ) {
                        ( sphaera:Part )
                        ( sphaera:Part_Adaption )
                    }
                    BIND(<http://sphaera.mpiwg-berlin.mpg.de/id/part/1eaef0cc-5d5d-45fb-a33c-0fe5b62add79> as ?part)
    
   }
  } GROUP BY ?influenced_part ?influenced_part_label ?custom_identifier ?carried_out_by
