import os
import json
import re
import glob

thesis_dir = "/Users/nogashlomi/projects/nog_thesis"
notebooks_dir = "/Users/nogashlomi/projects/publication_data/dissertation"

# 1. Parse Typst files to find Figures, their image paths, and captions
figures_data = []
typ_files = glob.glob(os.path.join(thesis_dir, "*.typ"))
# Sort them roughly by chapter if possible, though the exact figure number is auto-generated by Typst.
typ_files.sort() 

for typ_file in typ_files:
    with open(typ_file, "r", encoding="utf-8") as f:
        content = f.read()
        
        # We look for blocks containing image("...") and extract the path and the surrounding text for context
        # A simple regex to find image("...")
        for match in re.finditer(r'image\(\s*"([^"]+)"', content):
            img_path = match.group(1)
            img_filename = os.path.basename(img_path)
            
            if "figures/plots/" not in img_path and "figures/corrections_round" not in img_path:
                continue
                
            # Try to extract a caption near this image
            # Find the index of this match
            idx = match.start()
            # Look at a window of text around it (e.g. 500 characters forward)
            window = content[idx:idx+500]
            caption_match = re.search(r'caption:\s*\[(.*?)\]', window, re.DOTALL)
            if not caption_match:
                caption_match = re.search(r'caption:\s*two_part_fig_caption\(\[(.*?)\]', window, re.DOTALL)
            
            caption = caption_match.group(1).replace('\n', ' ').strip() if caption_match else "No caption found"
            # Truncate caption for table readability
            if len(caption) > 100:
                caption = caption[:97] + "..."
                
            figures_data.append({
                "file": os.path.basename(typ_file),
                "img_filename": img_filename,
                "caption": caption
            })

# 2. Scan Notebooks
notebook_mapping = {}
ipynb_files = glob.glob(os.path.join(notebooks_dir, "*.ipynb"))

for ipynb_file in ipynb_files:
    try:
        with open(ipynb_file, "r", encoding="utf-8") as f:
            nb = json.load(f)
            nb_name = os.path.basename(ipynb_file)
            for cell in nb.get("cells", []):
                if cell["cell_type"] == "code":
                    source = "".join(cell.get("source", []))
                    for fig in figures_data:
                        if fig["img_filename"] in source:
                            if fig["img_filename"] not in notebook_mapping:
                                notebook_mapping[fig["img_filename"]] = set()
                            notebook_mapping[fig["img_filename"]].add(nb_name)
    except Exception as e:
        pass

# 3. Generate Markdown Table
output_file = "/Users/nogashlomi/projects/publication_data/FIGURE_MAPPING.md"

with open(output_file, "w", encoding="utf-8") as out:
    out.write("# Thesis Figures to Notebooks Mapping\n\n")
    out.write("This table maps the figures generated in the thesis to the Jupyter Notebooks that produced them.\n\n")
    out.write("| Chapter File | Image File | Caption Snippet | Generated By Notebook(s) |\n")
    out.write("|---|---|---|---|\n")
    
    for fig in figures_data:
        notebooks = list(notebook_mapping.get(fig["img_filename"], []))
        notebooks_str = ", ".join([f"`{n}`" for n in notebooks]) if notebooks else "*Not found in scripts*"
        out.write(f"| {fig['file']} | `{fig['img_filename']}` | {fig['caption']} | {notebooks_str} |\n")

print(f"Mapping generated and saved to {output_file}")
